
-- CREATE DATABASE lab3
--     WITH 
--     OWNER = postgres
--     ENCODING = 'UTF8'
--     LC_COLLATE = 'Ukrainian_Ukraine.1251'
--     LC_CTYPE = 'Ukrainian_Ukraine.1251'
--     TABLESPACE = pg_default
--     CONNECTION LIMIT = -1;

-- CREATE TABLE IF NOT EXISTS lab3.FORUMS
-- (
--     id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
--     name text COLLATE pg_catalog."default" NOT NULL,
--     topicKeyword text NOT NULL,
--     users text[],
--     CONSTRAINT PK_forum PRIMARY KEY (id)
-- )

-- CREATE TABLE IF NOT EXISTS lab3.USERS
-- (
--     id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
--     nickname text NOT NULL,
--     keywords text[] NOT NULL,
--     CONSTRAINT PK_user PRIMARY KEY (id)
-- )

-- INSERT INTO lab3.FORUMS (name, topicKeyword, users)
-- VALUES ('games', 'game_kw', ('u1', 'u2'));

DROP TABLE IF EXISTS "channels";
CREATE TABLE "channels"
(
    "id"   SERIAL PRIMARY KEY,
    "name" VARCHAR(50) NOT NULL UNIQUE
);

-- Insert demo data.
INSERT INTO "channels" (name) VALUES ('lectures');
INSERT INTO "channels" (name) VALUES ('practice');