name: GoCI
on: [push,  pull_request]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-go@v2
        with: 
          go-version: 1.17.1

      - name: Clean
        working-directory: ./lab2
        run: make clean

      - name: Test
        working-directory: ./lab2
        run: make test

      - name: Build
        working-directory: ./lab2
        run: make
